# Generated by Django 4.2.13 on 2024-07-16 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0021_remove_startup_deal_owner_remove_startup_deal_viewer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherCompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_of_company', models.PositiveIntegerField(help_text='Number of years since the company was founded.')),
                ('founders_and_team', models.TextField(help_text='Names and roles of the founders and key team members.')),
                ('story_of_founder', models.TextField(help_text='Personal and professional background of the founder.')),
                ('about_the_company', models.TextField(help_text='General information about the company.')),
                ('market_landscape', models.TextField(help_text='Description of the market landscape in which the company operates.')),
                ('market_size', models.CharField(help_text='Estimated size of the market.', max_length=255)),
                ('problem_being_solved', models.TextField(help_text='The problem the company aims to solve.')),
                ('solution_business_model', models.TextField(help_text='Description of the solution or business model, including any revenue-generating activities.')),
                ('revenue_generating_activities', models.TextField(help_text='Activities through which the company generates revenue.')),
                ('revenue_streams', models.TextField(help_text='Different streams of revenue for the company.')),
                ('traction', models.TextField(help_text='Key performance indicators and impact of the company.')),
                ('unit_economics', models.TextField(help_text='Details on the unit economics of the business.')),
                ('business_trajectory', models.TextField(help_text='Business trajectory over the last 2-3 years.')),
                ('competition', models.TextField(help_text='Information about the competition.')),
                ('total_funding_raised', models.DecimalField(decimal_places=2, help_text='Total amount of funding raised by the company.', max_digits=20)),
                ('investors', models.TextField(help_text='Names of the investors.')),
                ('achievements_and_recognition', models.TextField(help_text='Achievements and recognition received by the company.')),
                ('fund_requirement', models.DecimalField(decimal_places=2, help_text='Amount of funding required.', max_digits=20)),
                ('fund_utilisation', models.TextField(help_text='Plan for the utilisation of the funds.')),
                ('next_plan', models.TextField(help_text='Future plans of the company.')),
                ('positives', models.TextField(help_text='Strengths or positive aspects of the company.')),
                ('concerns_risks', models.TextField(help_text='Concerns or risks associated with the company.')),
                ('genesis_of_startup', models.TextField(help_text='Explanation of why the startup was founded.')),
                ('is_business_impact_first', models.BooleanField(default=False, help_text='Indicates if the business prioritizes impact over other objectives.')),
                ('reason_for_business_not_non_profit', models.TextField(help_text='Reason for choosing a business model instead of a non-profit model.')),
                ('pivots_in_business_journey', models.TextField(help_text='Details of any pivots made in the business journey and the reasons behind them, especially if decisions were made to retain impact.')),
                ('beneficiary_role', models.CharField(help_text='Role of the beneficiary in the value chain, such as customer, employee, etc.', max_length=255)),
                ('startup', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.startup')),
            ],
        ),
    ]
