# Generated by Django 4.2.13 on 2024-07-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othercompanyinfo',
            name='about_the_company',
            field=models.TextField(blank=True, help_text='General information about the company.', null=True),
        ),
        migrations.AlterField(
            model_name='othercompanyinfo',
            name='achievements_and_recognition',
            field=models.TextField(blank=True, help_text='Achievements and recognition received by the company.', null=True),
        ),
        migrations.AlterField(
            model_name='othercompanyinfo',
            name='age_of_company',
            field=models.PositiveIntegerField(blank=True, help_text='Number of years since the company was founded.', null=True),
        ),
        migrations.AlterField(
            model_name='othercompanyinfo',
            name='beneficiary_role',
            field=models.CharField(blank=True, help_text='Role of the beneficiary in the value chain, such as customer, employee, etc.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='othercompanyinfo',
            name='business_trajectory',
            field=models.TextField(blank=True, help_text='Business trajectory over the last 2-3 years.', null=True),
        ),
        migrations.AlterField(
            model_name='othercompanyinfo',
            name='competition',
            field=models.TextField(blank=True, help_text='Information about the competition.', null=True),
        ),
        migrations.AlterField(
            model_name='othercompanyinfo',
            name='concerns_risks',
            field=models.TextField(blank=True, help_text='Concerns or risks associated with the company.', null=True),
        ),
        migrations.AlterField(
            model_name='othercompanyinfo',
            name='founders_and_team',
            field=models.TextField(blank=True, help_text='Names and roles of the founders and key team members.', null=True),
        ),
        migrations.AlterField(
            model_name='othercompanyinfo',
            name='fund_requirement',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount of funding required.', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='othercompanyinfo',
            name='fund_utilisation',
            field=models.TextField(blank=True, help_text='Plan for the utilisation of the funds.', null=True),
        ),
        migrations.AlterField(
            model_name='othercompanyinfo',
            name='genesis_of_startup',
            field=models.TextField(blank=True, help_text='Explanation of why the startup was founded.', null=True),
        ),
        migrations.AlterField(
            model_name='othercompanyinfo',
            name='investors',
            field=models.TextField(blank=True, help_text='Names of the investors.', null=True),
        ),
        migrations.AlterField(
            model_name='othercompanyinfo',
            name='is_business_impact_first',
            field=models.BooleanField(blank=True, default=False, help_text='Indicates if the business prioritizes impact over other objectives.', null=True),
        ),
        migrations.AlterField(
            model_name='othercompanyinfo',
            name='market_landscape',
            field=models.TextField(blank=True, help_text='Description of the market landscape in which the company operates.', null=True),
        ),
        migrations.AlterField(
            model_name='othercompanyinfo',
            name='market_size',
            field=models.CharField(blank=True, help_text='Estimated size of the market.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='othercompanyinfo',
            name='next_plan',
            field=models.TextField(blank=True, help_text='Future plans of the company.', null=True),
        ),
        migrations.AlterField(
            model_name='othercompanyinfo',
            name='pivots_in_business_journey',
            field=models.TextField(blank=True, help_text='Details of any pivots made in the business journey and the reasons behind them, especially if decisions were made to retain impact.', null=True),
        ),
        migrations.AlterField(
            model_name='othercompanyinfo',
            name='positives',
            field=models.TextField(blank=True, help_text='Strengths or positive aspects of the company.', null=True),
        ),
        migrations.AlterField(
            model_name='othercompanyinfo',
            name='problem_being_solved',
            field=models.TextField(blank=True, help_text='The problem the company aims to solve.', null=True),
        ),
        migrations.AlterField(
            model_name='othercompanyinfo',
            name='reason_for_business_not_non_profit',
            field=models.TextField(blank=True, help_text='Reason for choosing a business model instead of a non-profit model.', null=True),
        ),
        migrations.AlterField(
            model_name='othercompanyinfo',
            name='revenue_generating_activities',
            field=models.TextField(blank=True, help_text='Activities through which the company generates revenue.', null=True),
        ),
        migrations.AlterField(
            model_name='othercompanyinfo',
            name='revenue_streams',
            field=models.TextField(blank=True, help_text='Different streams of revenue for the company.', null=True),
        ),
        migrations.AlterField(
            model_name='othercompanyinfo',
            name='solution_business_model',
            field=models.TextField(blank=True, help_text='Description of the solution or business model, including any revenue-generating activities.', null=True),
        ),
        migrations.AlterField(
            model_name='othercompanyinfo',
            name='story_of_founder',
            field=models.TextField(blank=True, help_text='Personal and professional background of the founder.', null=True),
        ),
        migrations.AlterField(
            model_name='othercompanyinfo',
            name='total_funding_raised',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount of funding raised by the company.', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='othercompanyinfo',
            name='traction',
            field=models.TextField(blank=True, help_text='Key performance indicators and impact of the company.', null=True),
        ),
        migrations.AlterField(
            model_name='othercompanyinfo',
            name='unit_economics',
            field=models.TextField(blank=True, help_text='Details on the unit economics of the business.', null=True),
        ),
    ]
