# Generated by Django 4.2.13 on 2024-07-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_alter_othercompanyinfo_about_the_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='othercompanyinfo',
            old_name='concerns_risks',
            new_name='concerns_or_risks',
        ),
        migrations.AddField(
            model_name='othercompanyinfo',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
