# Generated by Django 4.2.13 on 2024-07-22 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0045_directinvestment'),
        ('extras', '0003_rename_concerns_risks_othercompanyinfo_concerns_or_risks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherCompanyInfoDirectInvestments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_of_company', models.PositiveIntegerField(blank=True, help_text='Number of years since the company was founded.', null=True)),
                ('founders_and_team', models.TextField(blank=True, help_text='Names and roles of the founders and key team members.', null=True)),
                ('story_of_founder', models.TextField(blank=True, help_text='Personal and professional background of the founder.', null=True)),
                ('about_the_company', models.TextField(blank=True, help_text='General information about the company.', null=True)),
                ('market_landscape', models.TextField(blank=True, help_text='Description of the market landscape in which the company operates.', null=True)),
                ('market_size', models.CharField(blank=True, help_text='Estimated size of the market.', max_length=255, null=True)),
                ('problem_being_solved', models.TextField(blank=True, help_text='The problem the company aims to solve.', null=True)),
                ('solution_business_model', models.TextField(blank=True, help_text='Description of the solution or business model, including any revenue-generating activities.', null=True)),
                ('revenue_generating_activities', models.TextField(blank=True, help_text='Activities through which the company generates revenue.', null=True)),
                ('revenue_streams', models.TextField(blank=True, help_text='Different streams of revenue for the company.', null=True)),
                ('traction', models.TextField(blank=True, help_text='Key performance indicators and impact of the company.', null=True)),
                ('unit_economics', models.TextField(blank=True, help_text='Details on the unit economics of the business.', null=True)),
                ('business_trajectory', models.TextField(blank=True, help_text='Business trajectory over the last 2-3 years.', null=True)),
                ('competition', models.TextField(blank=True, help_text='Information about the competition.', null=True)),
                ('total_funding_raised', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount of funding raised by the company.', max_digits=20, null=True)),
                ('investors', models.TextField(blank=True, help_text='Names of the investors.', null=True)),
                ('achievements_and_recognition', models.TextField(blank=True, help_text='Achievements and recognition received by the company.', null=True)),
                ('fund_requirement', models.DecimalField(blank=True, decimal_places=2, help_text='Amount of funding required.', max_digits=20, null=True)),
                ('fund_utilisation', models.TextField(blank=True, help_text='Plan for the utilisation of the funds.', null=True)),
                ('next_plan', models.TextField(blank=True, help_text='Future plans of the company.', null=True)),
                ('positives', models.TextField(blank=True, help_text='Strengths or positive aspects of the company.', null=True)),
                ('concerns_or_risks', models.TextField(blank=True, help_text='Concerns or risks associated with the company.', null=True)),
                ('genesis_of_startup', models.TextField(blank=True, help_text='Explanation of why the startup was founded.', null=True)),
                ('is_business_impact_first', models.BooleanField(blank=True, default=False, help_text='Indicates if the business prioritizes impact over other objectives.', null=True)),
                ('reason_for_business_not_non_profit', models.TextField(blank=True, help_text='Reason for choosing a business model instead of a non-profit model.', null=True)),
                ('pivots_in_business_journey', models.TextField(blank=True, help_text='Details of any pivots made in the business journey and the reasons behind them, especially if decisions were made to retain impact.', null=True)),
                ('beneficiary_role', models.CharField(blank=True, help_text='Role of the beneficiary in the value chain, such as customer, employee, etc.', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('startup', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.directinvestment')),
            ],
        ),
    ]
