# Generated by Django 4.2.13 on 2024-07-30 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0050_remove_emailtemplate_link'),
        ('extras', '0005_messagestatusinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagestatusinfo',
            old_name='status',
            new_name='application_status',
        ),
        migrations.RenameField(
            model_name='messagestatusinfo',
            old_name='message_status',
            new_name='sent_status',
        ),
        migrations.AlterField(
            model_name='messagestatusinfo',
            name='startup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.startup'),
        ),
    ]
