# Generated by Django 4.2.13 on 2024-07-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0006_rename_status_messagestatusinfo_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagestatusinfo',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
