# Generated by Django 4.2.13 on 2024-07-05 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('incorporation_date', models.CharField(blank=True, max_length=50, null=True)),
                ('last_agm_date', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('registered_address', models.TextField(blank=True, null=True)),
                ('balance_sheet_date', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('company_class', models.CharField(blank=True, max_length=50, null=True)),
                ('company_type', models.CharField(blank=True, max_length=50, null=True)),
                ('paid_up_capital', models.CharField(blank=True, max_length=50, null=True)),
                ('authorised_capital', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('roc_office', models.CharField(blank=True, max_length=100, null=True)),
                ('country_of_incorporation', models.CharField(blank=True, max_length=50, null=True)),
                ('description_of_main_division', models.CharField(blank=True, max_length=255, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=255, null=True)),
                ('address_other_than_registered_office', models.TextField(blank=True, null=True)),
                ('number_of_members', models.CharField(blank=True, max_length=50, null=True)),
                ('active_compliance', models.CharField(blank=True, max_length=50, null=True)),
                ('suspended_at_stock_exchange', models.CharField(blank=True, max_length=50, null=True)),
                ('nature_of_business', models.CharField(blank=True, max_length=255, null=True)),
                ('status_for_efiling', models.CharField(blank=True, max_length=50, null=True)),
                ('status_under_cirp', models.CharField(blank=True, max_length=50, null=True)),
                ('pan', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('din', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_appointment', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pan', models.CharField(blank=True, max_length=50, null=True)),
                ('no_of_companies', models.IntegerField(blank=True, default=0, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.CharField(blank=True, max_length=50, null=True)),
                ('split_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='search.company')),
            ],
        ),
        migrations.CreateModel(
            name='GSTData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('gst_estimated_total', models.CharField(blank=True, max_length=255, null=True)),
                ('gst_filed_total', models.CharField(blank=True, max_length=255, null=True)),
                ('pan_estimated_total', models.CharField(blank=True, max_length=255, null=True)),
                ('pan_filed_total', models.CharField(blank=True, max_length=255, null=True)),
                ('gst_status', models.CharField(blank=True, max_length=50, null=True)),
                ('legal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('trade_name', models.CharField(blank=True, max_length=255, null=True)),
                ('register_date', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_payer_type', models.CharField(blank=True, max_length=50, null=True)),
                ('authorized_signatory', models.CharField(blank=True, max_length=1000, null=True)),
                ('business_nature', models.CharField(blank=True, max_length=1000, null=True)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_data', to='search.director')),
            ],
        ),
    ]
