# Generated by Django 4.2.13 on 2024-07-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_director_company_list_director_masked_aadhaar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='is_sole_proprietor',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='other_director_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
