# Generated by Django 4.2.13 on 2024-07-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_remove_gstdata_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstdata',
            name='company_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
