# Generated by Django 4.2.13 on 2024-07-13 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0009_alter_company_options_company_debt_company_equity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='additional_comments',
        ),
        migrations.RemoveField(
            model_name='company',
            name='attachment1',
        ),
        migrations.RemoveField(
            model_name='company',
            name='attachment2',
        ),
        migrations.RemoveField(
            model_name='company',
            name='attachment3',
        ),
        migrations.RemoveField(
            model_name='company',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='company',
            name='deal_owner',
        ),
        migrations.RemoveField(
            model_name='company',
            name='debt',
        ),
        migrations.RemoveField(
            model_name='company',
            name='equity',
        ),
        migrations.RemoveField(
            model_name='company',
            name='grants',
        ),
        migrations.RemoveField(
            model_name='company',
            name='in_review_comment',
        ),
        migrations.RemoveField(
            model_name='company',
            name='in_review_date',
        ),
        migrations.RemoveField(
            model_name='company',
            name='language',
        ),
        migrations.RemoveField(
            model_name='company',
            name='last_edited_by',
        ),
        migrations.RemoveField(
            model_name='company',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='company',
            name='pre_r1_stage_comment',
        ),
        migrations.RemoveField(
            model_name='company',
            name='pre_r1_stage_date',
        ),
        migrations.RemoveField(
            model_name='company',
            name='r1_comment',
        ),
        migrations.RemoveField(
            model_name='company',
            name='r1_date',
        ),
        migrations.RemoveField(
            model_name='company',
            name='r2_comment',
        ),
        migrations.RemoveField(
            model_name='company',
            name='r2_date',
        ),
        migrations.RemoveField(
            model_name='company',
            name='rejected_comment',
        ),
        migrations.RemoveField(
            model_name='company',
            name='rejected_date',
        ),
        migrations.RemoveField(
            model_name='company',
            name='relevant_link1',
        ),
        migrations.RemoveField(
            model_name='company',
            name='relevant_link2',
        ),
        migrations.RemoveField(
            model_name='company',
            name='relevant_link3',
        ),
        migrations.RemoveField(
            model_name='company',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='company',
            name='site_visit_comment',
        ),
        migrations.RemoveField(
            model_name='company',
            name='site_visit_date',
        ),
        migrations.RemoveField(
            model_name='company',
            name='source',
        ),
        migrations.RemoveField(
            model_name='company',
            name='status_comment',
        ),
        migrations.RemoveField(
            model_name='company',
            name='twelve_m_revenue',
        ),
        migrations.RemoveField(
            model_name='company',
            name='video_url',
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('founder_name', models.CharField(blank=True, max_length=200, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('current_status', models.CharField(blank=True, choices=[('in_review', 'In-review'), ('pre_r1_stage', 'Pre-R1 stage'), ('r1', 'R1'), ('r2', 'R2'), ('site_visit', 'Site visit'), ('rejected', 'Rejected')], max_length=50, null=True)),
                ('status_comment', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('attachment1', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('attachment2', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('attachment3', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('relevant_link1', models.URLField(blank=True, null=True)),
                ('relevant_link2', models.URLField(blank=True, null=True)),
                ('relevant_link3', models.URLField(blank=True, null=True)),
                ('in_review_comment', models.TextField(blank=True, null=True)),
                ('pre_r1_stage_comment', models.TextField(blank=True, null=True)),
                ('r1_comment', models.TextField(blank=True, null=True)),
                ('r2_comment', models.TextField(blank=True, null=True)),
                ('site_visit_comment', models.TextField(blank=True, null=True)),
                ('rejected_comment', models.TextField(blank=True, null=True)),
                ('in_review_date', models.DateField(blank=True, null=True)),
                ('pre_r1_stage_date', models.DateField(blank=True, null=True)),
                ('r1_date', models.DateField(blank=True, null=True)),
                ('r2_date', models.DateField(blank=True, null=True)),
                ('site_visit_date', models.DateField(blank=True, null=True)),
                ('rejected_date', models.DateField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('twelve_m_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('equity', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('debt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('grants', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('no_of_founders', models.IntegerField(blank=True, null=True)),
                ('team_size', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('founding_year', models.IntegerField(blank=True, null=True)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('last_edited_on', models.DateTimeField(auto_now=True)),
                ('deal_owner', models.ManyToManyField(blank=True, related_name='deal_companies', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_companies', to=settings.AUTH_USER_MODEL)),
                ('legal_entity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.company')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.source')),
            ],
        ),
    ]
