# Generated by Django 4.2.13 on 2024-07-13 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_remove_company_additional_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startup',
            old_name='twelve_m_revenue',
            new_name='ARR',
        ),
        migrations.AddField(
            model_name='startup',
            name='source_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='src_name', to='search.source'),
        ),
    ]
