# Generated by Django 4.2.13 on 2024-07-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_rename_twelve_m_revenue_startup_arr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='status_comment',
        ),
    ]
