# Generated by Django 4.2.13 on 2024-07-13 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_remove_startup_status_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='startup',
            name='source_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='src_name', to='search.sourcename'),
        ),
    ]
