# Generated by Django 4.2.13 on 2024-07-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0013_sourcename_alter_startup_source_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
