# Generated by Django 4.2.13 on 2024-07-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_startup_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupCounts',
            fields=[
            ],
            options={
                'verbose_name': 'Startup Counts',
                'verbose_name_plural': 'Startup Counts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('search.startup',),
        ),
    ]
