# Generated by Django 4.2.13 on 2024-07-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_startupcounts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StartupCounts',
        ),
        migrations.CreateModel(
            name='StartupStatusCounts',
            fields=[
            ],
            options={
                'verbose_name': 'Startup Status Counts',
                'verbose_name_plural': 'Startup Status Counts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('search.startup',),
        ),
    ]
