# Generated by Django 4.2.13 on 2024-07-16 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0020_startup_deal_viewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='deal_owner',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='deal_viewer',
        ),
        migrations.AddField(
            model_name='startup',
            name='deal_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='startup',
            name='deal_viewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.team'),
        ),
    ]
