# Generated by Django 4.2.13 on 2024-07-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0021_remove_startup_deal_owner_remove_startup_deal_viewer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='community_mindset',
            field=models.BooleanField(blank=True, help_text='Will they give their time to someone they don`t know, who is seeking advice?', null=True, verbose_name='Community Mindset'),
        ),
        migrations.AddField(
            model_name='startup',
            name='fund_alignment',
            field=models.BooleanField(blank=True, help_text='Is their business model directly increasing the income of India 2 or India 3?', null=True, verbose_name='Fund Alignment'),
        ),
        migrations.AddField(
            model_name='startup',
            name='intent_driven',
            field=models.BooleanField(blank=True, help_text='Are they Intent driven?', null=True, verbose_name='Intent Driven'),
        ),
        migrations.AddField(
            model_name='startup',
            name='systemic_change_potential',
            field=models.BooleanField(blank=True, help_text='If their business succeeds, will they continue to seek other ways to help solve the same social problem?', null=True, verbose_name='Systemic Change Potential'),
        ),
    ]
