# Generated by Django 4.2.13 on 2024-07-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0022_startup_community_mindset_startup_fund_alignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='source_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='SourceName',
        ),
    ]
