# Generated by Django 4.2.13 on 2024-07-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0023_alter_startup_source_name_delete_sourcename'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='source_type',
            field=models.CharField(blank=True, choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], max_length=8, null=True),
        ),
    ]
