# Generated by Django 4.2.13 on 2024-07-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0024_startup_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='knockout_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='ARR',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='current_status',
            field=models.CharField(blank=True, choices=[('in_review', 'In-review'), ('pre_r1_stage', 'Pre-R1 stage'), ('r1', 'R1'), ('r2', 'R2'), ('site_visit', 'Site visit'), ('rejected', 'Rejected'), ('knockout', 'Knockout')], max_length=50, null=True),
        ),
    ]
