# Generated by Django 4.2.13 on 2024-07-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0025_startup_knockout_date_alter_startup_arr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startup',
            old_name='notes',
            new_name='approved_for_residency_comment',
        ),
        migrations.RenameField(
            model_name='startup',
            old_name='attachment3',
            new_name='pitch_deck',
        ),
        migrations.RenameField(
            model_name='startup',
            old_name='relevant_link3',
            new_name='website',
        ),
        migrations.AddField(
            model_name='startup',
            name='approved_for_investments_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='approved_for_investments_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='approved_for_residency_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='ic_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='ic_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='last_interaction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='monitor_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='monitor_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='nominator_list_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='nomintor_list_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='pre_ic_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='pre_ic_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='sub_sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='to_conduct_r1_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='to_conduct_r1_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='current_status',
            field=models.CharField(blank=True, choices=[('approved_for_investments', 'Approved for investments'), ('approved_for_residency', 'Approved for residency'), ('in_review', 'In-review'), ('pre_r1_stage', 'Pre-R1 stage'), ('ic', 'IC'), ('pre_ic', 'Pre-IC'), ('r1', 'R1'), ('r2', 'R2'), ('site_visit', 'Site visit'), ('to_conduct_r1', 'To conduct R1'), ('nominator_list', 'Nominator list'), ('monitor', 'Monitor'), ('rejected', 'Rejected'), ('knockout', 'Knockout')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='sector',
            field=models.CharField(blank=True, choices=[('other', 'Other'), ('waste_management', 'Waste Management'), ('rural_supply_chain', 'Rural Supply Chain'), ('mobility', 'Mobility'), ('food_and_agriculture', 'Food and Agriculture'), ('health', 'Health'), ('financial_inclusion', 'Financial Inclusion')], max_length=100, null=True),
        ),
    ]
