# Generated by Django 4.2.13 on 2024-07-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0026_rename_notes_startup_approved_for_residency_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='nominator_list_date',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='nomintor_list_comment',
        ),
        migrations.AlterField(
            model_name='startup',
            name='current_status',
            field=models.CharField(blank=True, choices=[('approved_for_investments', 'Approved for investments'), ('approved_for_residency', 'Approved for residency'), ('in_review', 'In-review'), ('pre_r1_stage', 'Pre-R1 stage'), ('ic', 'IC'), ('pre_ic', 'Pre-IC'), ('r1', 'R1'), ('r2', 'R2'), ('site_visit', 'Site visit'), ('to_conduct_r1', 'To conduct R1'), ('monitor', 'Monitor'), ('rejected', 'Rejected'), ('knockout', 'Knockout')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='sector',
            field=models.CharField(blank=True, choices=[('other', 'Other'), ('waste_management', 'Waste Management'), ('supply_chain', 'Supply Chain'), ('mobility', 'Mobility'), ('agriculture', 'Agriculture'), ('health', 'Health'), ('financial_inclusion', 'Financial Inclusion')], max_length=100, null=True),
        ),
    ]
