# Generated by Django 4.2.13 on 2024-07-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0027_remove_startup_nominator_list_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='equity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='founding_year',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
