# Generated by Django 4.2.13 on 2024-07-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0028_alter_startup_equity_alter_startup_founding_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='debt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='grants',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
