# Generated by Django 4.2.13 on 2024-07-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0029_alter_startup_debt_alter_startup_grants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='no_of_founders',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
