# Generated by Django 4.2.13 on 2024-07-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0030_alter_startup_no_of_founders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
