# Generated by Django 4.2.13 on 2024-07-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0031_alter_startup_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='sub_sector',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
