# Generated by Django 4.2.13 on 2024-07-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0032_alter_startup_sub_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='stage',
            field=models.CharField(blank=True, choices=[('idea', 'Idea'), ('pre_seed', 'Pre-seed'), ('seed', 'Seed'), ('seed+', 'Seed+'), ('pre_series_a', 'Pre-series A'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('series_c_and_above', 'Series C and above')], max_length=50, null=True),
        ),
    ]
