# Generated by Django 4.2.13 on 2024-07-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0033_startup_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startup',
            old_name='phone_number',
            new_name='additional_number',
        ),
    ]
