# Generated by Django 4.2.13 on 2024-07-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0037_alter_startup_community_mindset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='attachment1',
            field=models.FileField(blank=True, null=True, upload_to='attachments/', verbose_name='Additional Attachment'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='attachment2',
            field=models.FileField(blank=True, null=True, upload_to='attachments/', verbose_name='Additional Attachment'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='relevant_link1',
            field=models.URLField(blank=True, null=True, verbose_name='Additional Link'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='relevant_link2',
            field=models.URLField(blank=True, null=True, verbose_name='Additional Link'),
        ),
    ]
