# Generated by Django 4.2.13 on 2024-07-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0038_alter_startup_attachment1_alter_startup_attachment2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='intent_driven',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], default='na', help_text='Are they Intent driven?', max_length=3, verbose_name='Intent Driven'),
        ),
    ]
