# Generated by Django 4.2.13 on 2024-07-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0039_alter_startup_intent_driven'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='approved_for_investments_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Approved For Investments'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='approved_for_residency_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Approved For Residency'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='ic_comment',
            field=models.TextField(blank=True, null=True, verbose_name='IC'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='in_review_comment',
            field=models.TextField(blank=True, null=True, verbose_name='In Review'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='monitor_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Monitor'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='pre_ic_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Pre IC'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='pre_r1_stage_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Pre-Rround1 Stage'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='r1_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Round1'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='r2_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Round2'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='rejected_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Rejected'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='site_visit_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Site Visit'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='to_conduct_r1_comment',
            field=models.TextField(blank=True, null=True, verbose_name='To Conduct Round1'),
        ),
    ]
