# Generated by Django 4.2.13 on 2024-07-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0040_alter_startup_approved_for_investments_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='pre_r1_stage_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Pre-Rround 1 Stage'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='r1_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Round 1'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='r2_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Round 2'),
        ),
    ]
