# Generated by Django 4.2.13 on 2024-07-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0041_alter_startup_pre_r1_stage_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='in_review_comment',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='to_conduct_r1_comment',
        ),
    ]
