# Generated by Django 4.2.13 on 2024-07-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0042_remove_startup_in_review_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='approved_for_investments_date',
            field=models.DateField(blank=True, null=True, verbose_name='Approved for Investments'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='approved_for_residency_date',
            field=models.DateField(blank=True, null=True, verbose_name='Approved for Residency'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='ic_date',
            field=models.DateField(blank=True, null=True, verbose_name='IC'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='in_review_date',
            field=models.DateField(blank=True, null=True, verbose_name='In Review'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='knockout_date',
            field=models.DateField(blank=True, null=True, verbose_name='Knockout'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='monitor_date',
            field=models.DateField(blank=True, null=True, verbose_name='Monitor'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='pre_ic_date',
            field=models.DateField(blank=True, null=True, verbose_name='Pre-IC'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='pre_r1_stage_date',
            field=models.DateField(blank=True, null=True, verbose_name='Pre-Round 1 Stage'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='r1_date',
            field=models.DateField(blank=True, null=True, verbose_name='Round 1'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='r2_date',
            field=models.DateField(blank=True, null=True, verbose_name='Round 2'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='rejected_date',
            field=models.DateField(blank=True, null=True, verbose_name='Rejected'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='site_visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Site Visit'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='to_conduct_r1_date',
            field=models.DateField(blank=True, null=True, verbose_name='To Conduct Round 1'),
        ),
    ]
