# Generated by Django 4.2.13 on 2024-07-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0043_alter_startup_approved_for_investments_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='site_visited_date',
            field=models.DateField(blank=True, null=True, verbose_name='Site Visited'),
        ),
    ]
