# Generated by Django 4.2.13 on 2024-07-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0045_directinvestment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startup',
            options={'verbose_name': 'Program application', 'verbose_name_plural': 'Program applications'},
        ),
        migrations.AlterModelOptions(
            name='startupstatuscounts',
            options={'verbose_name': 'Dashboard', 'verbose_name_plural': 'Dashboard'},
        ),
        migrations.AlterField(
            model_name='startup',
            name='current_status',
            field=models.CharField(blank=True, choices=[('in_review', 'In-review'), ('to_conduct_r1', 'To conduct R1'), ('pre_r1_stage', 'Pre-R1 stage'), ('r1', 'R1'), ('r2', 'R2'), ('pre_ic', 'Pre-IC'), ('ic', 'IC'), ('site_visit', 'Site visit'), ('approved_for_investments', 'Approved for investments'), ('approved_for_residency', 'Approved for residency'), ('monitor', 'Monitor'), ('rejected', 'Rejected'), ('knockout', 'Knockout')], max_length=50, null=True),
        ),
    ]
