# Generated by Django 4.2.13 on 2024-07-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0046_alter_startup_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_review', 'In-review'), ('to_conduct_r1', 'To conduct R1'), ('pre_r1_stage', 'Pre-R1 stage'), ('r1', 'R1'), ('r2', 'R2'), ('pre_ic', 'Pre-IC'), ('ic', 'IC'), ('site_visit', 'Site visit'), ('approved_for_investments', 'Approved for investments'), ('approved_for_residency', 'Approved for residency'), ('monitor', 'Monitor'), ('rejected', 'Rejected'), ('knockout', 'Knockout')], max_length=50, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Calendly Link'),
        ),
    ]
