# Generated by Django 4.2.13 on 2024-07-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0047_emailtemplate_team_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directinvestment',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='source_type',
        ),
        migrations.AlterField(
            model_name='startup',
            name='current_status',
            field=models.CharField(blank=True, choices=[('in_review', 'In-review'), ('to_conduct_r1', 'To conduct R1'), ('pre_r1_stage', 'Pre-R1 stage'), ('r1', 'R1'), ('site_visit', 'Site visit'), ('r2', 'R2'), ('pre_ic', 'Pre-IC'), ('ic', 'IC'), ('approved_for_investments', 'Approved for investments'), ('approved_for_residency', 'Approved for residency'), ('monitor', 'Monitor'), ('rejected', 'Rejected'), ('knockout', 'Knockout')], max_length=50, null=True),
        ),
    ]
