# Generated by Django 4.2.13 on 2024-07-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0049_remove_team_link_emailtemplate_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='link',
        ),
    ]
