# Generated by Django 4.2.13 on 2024-07-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0050_remove_emailtemplate_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directinvestment',
            old_name='to_conduct_r1_date',
            new_name='scheduled_r1_date',
        ),
        migrations.RenameField(
            model_name='startup',
            old_name='to_conduct_r1_date',
            new_name='scheduled_r1_date',
        ),
        migrations.AlterField(
            model_name='directinvestment',
            name='current_status',
            field=models.CharField(blank=True, choices=[('approved_for_investments', 'Approved for investments'), ('approved_for_residency', 'Approved for residency'), ('in_review', 'In-review'), ('pre_r1_stage', 'Pre-R1 stage'), ('ic', 'IC'), ('pre_ic', 'Pre-IC'), ('r1', 'R1'), ('r2', 'R2'), ('site_visit', 'Site visit'), ('scheduled_r1', 'To conduct R1'), ('monitor', 'Monitor'), ('rejected', 'Rejected'), ('knockout', 'Knockout')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='status',
            field=models.CharField(choices=[('in_review', 'In-review'), ('scheduled_r1', 'To conduct R1'), ('pre_r1_stage', 'Pre-R1 stage'), ('r1', 'R1'), ('r2', 'R2'), ('pre_ic', 'Pre-IC'), ('ic', 'IC'), ('site_visit', 'Site visit'), ('approved_for_investments', 'Approved for investments'), ('approved_for_residency', 'Approved for residency'), ('monitor', 'Monitor'), ('rejected', 'Rejected'), ('knockout', 'Knockout')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='current_status',
            field=models.CharField(blank=True, choices=[('in_review', 'In-review'), ('scheduled_r1', 'To conduct R1'), ('pre_r1_stage', 'Pre-R1 stage'), ('r1', 'R1'), ('site_visit', 'Site visit'), ('r2', 'R2'), ('pre_ic', 'Pre-IC'), ('ic', 'IC'), ('approved_for_investments', 'Approved for investments'), ('approved_for_residency', 'Approved for residency'), ('monitor', 'Monitor'), ('rejected', 'Rejected'), ('knockout', 'Knockout')], max_length=50, null=True),
        ),
    ]
