# Generated by Django 4.2.13 on 2024-08-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0053_alter_startup_rejection_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='application_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
