# Generated by Django 5.0.7 on 2024-08-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0055_alter_startup_application_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='dipp_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='dipp_recognition_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='startup_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
