# Generated by Django 5.0.7 on 2024-08-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0056_startup_dipp_number_startup_dipp_recognition_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='dipp_number',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='dipp_recognition_status',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='startup_id',
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='dipp_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='dipp_recognition_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
