# Generated by Django 5.0.7 on 2024-08-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0057_remove_startup_dipp_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='startup_id',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
