# Generated by Django 5.0.7 on 2024-08-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0058_company_startup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cin',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
