# Generated by Django 5.0.7 on 2024-08-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0060_company_dipp_certified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='gst',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
