# Generated by Django 5.0.7 on 2024-08-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0061_company_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='aggregate_turnover_fy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='gstr_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ntc_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='turnover',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
