# Generated by Django 5.0.7 on 2024-08-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0062_company_aggregate_turnover_fy_company_gstr_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='din',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
