# Generated by Django 4.2.13 on 2024-08-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accelerator',
            name='date_of_establishment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incubator',
            name='date_of_establishment',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
    ]
