# Generated by Django 4.2.13 on 2024-08-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0002_alter_accelerator_date_of_establishment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incubator',
            name='date_of_establishment',
        ),
        migrations.AddField(
            model_name='incubator',
            name='incubation_centers_locations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
