# Generated by Django 4.2.13 on 2024-08-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0003_remove_incubator_date_of_establishment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accelerator',
            name='portfolio_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='incubator',
            name='portfolio_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
